### ISSUE TITLE
Dump/Crush the extensions hookeds

### ISSUE THREAD

**Issue by KratorD** [paustian/EZComments#10]
When you want create a new element of another extension where EZComments is a hook, the page dump with the follow message: (Example: NewsModule)
`request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Zikula\EZCommentsModule\HookProvider\UiHooksProvider::commentEdit() must be an instance of Zikula\Bundle\HookBundle\FormAwareHook\FormAwareHook, instance of Zikula\Bundle\HookBundle\Hook\DisplayHook given")." at /home/heroesmi/public_html/portal/modules/MU/NewsModule/Resources/views/Message/Admin/edit.html.twig line 186 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Argument 1 passed to Zikula\\EZCommentsModule\\HookProvider\\UiHooksProvider::commentEdit() must be an instance of Zikula\\Bundle\\HookBundle\\FormAwareHook\\FormAwareHook, instance of Zikula\\Bundle\\HookBundle\\Hook\\DisplayHook given\"). at /home/heroesmi/public_html/portal/modules/MU/NewsModule/Resources/views/Message/Admin/edit.html.twig:186, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Zikula\\EZCommentsModule\\HookProvider\\UiHooksProvider::commentEdit() must be an instance of Zikula\\Bundle\\HookBundle\\FormAwareHook\\FormAwareHook, instance of Zikula\\Bundle\\HookBundle\\Hook\\DisplayHook given at /home/heroesmi/public_html/portal/modules/zikula/EZComments-module/HookProvider/UiHooksProvider.php:149)"} []`

The error look dissapear when you change it:
From `public function commentEdit(FormAwareHook $hook)`
To `public function commentEdit(DisplayHook $hook)`

Thanks

**Comment by paustian** [comment]
Thanks for the information. I made the suggested change and the bug is now fixed.
