### ISSUE TITLE
Comments should allow paragraphs. Right now they are ignored. 

### ISSUE THREAD

**Issue by paustian** [paustian/EZComments#11]
When a comment is written, return characters are ignored and not formatting is allowed. The text appears as one big block. This needs to be improved to at least allow. I am sure there are solutions for this out there.

**Comment by paustian** [comment]
I am going to try to implement scribite use.

**Comment by paustian** [comment]
Scribite won't work since the comments are implmented in javascript.

**Comment by Guite** [comment]
Scribite offers a JavaScript interface. But it is probably too heavyweight.

How about using no editor?
You can just use `{{ comment|nl2br }}` to add HTML line breaks.
I think a complete editor may be too much to write a comment for most people, too.

**Comment by paustian** [comment]
I agree Guite. I am hoping to finish this up today.

**Comment by paustian** [comment]
Paragraphs now implmeneted.
