### ISSUE TITLE
Integration with MUNewsModule

### ISSUE THREAD

**Issue by KratorD** [paustian/EZComments#14]
I wrote this issue in MUNews, but craigh pointed that this feature must to be create in EZComments. I'm not sure about this. Could you review it with him?

https://github.com/zikula-modules/News/issues/51

Thanks

**Comment by paustian** [comment]
Can you be more descriptive? You can already hook into the news module and add comments to stories. That has been the one I have been testing with. (And the book module). Is there some other feature you are looking for?

**Comment by KratorD** [comment]
Yes, what I need is the following:
Your users have written 8 comments in a new of MUNewsModule. 
I have the news block where x(4,5,6...) of them are shown. For each new, I want show "8 comments", "2 comments", "1 comment"...
This feature was available in old News module (not in EZComments), the entity "news" will contain a new calculated field in the template -> "commentcount", with the number of comments of the new. This was possible because "old news module" contain specific logic for this.
According to craigh, this should not be like that. EZComments module should accomodate this request.
I hope you can understand this request now :)

**Comment by Guite** [comment]
An additional difficulty: for performance reasons the amount of comments for a certain object id should ideally be persisted and only recalculated/updated when comments are added or removed.

**Comment by paustian** [comment]
Krator. Before I implement this I want to make sure I understand. You have an item (let's say a news item) that your users have commented on. You want, at the top of the comments section, a listing of how many comments are attached to the news item. It would be easy to calculate this when the call to the hook came in. 

@Guite It's one db call, which I don't think is too bad. Is it really worth persisting? I doubt any id is going to have tens of thousands of comments attached to it and it is only in this range that a db call would become a performance issue. Trying to keep track of this would require adding another table 

I am also not sure how to add that variable to the template so folks could use it.

**Comment by Guite** [comment]
See discussion in Slack.

> You want, at the top of the comments section, a listing of how many comments are attached to the news item.

Very often the amount of comments is of interest at a separate place, e.g. in a news list, overview etc.

**Comment by paustian** [comment]
I have this implemented, but I think I still need to customize it. For example, right now it would be difficult to add the number of comments to a news list area. Any feedback on how to proceed is appreciated.

**Comment by Guite** [comment]
EZComments should provide two provider areas. Each subscribing module can then use the comment-list area and the comment-count area independently by assigning them to the desired subscriber areas.

**Comment by paustian** [comment]
@Guite See what I did in the implementation it's now posted.

**Comment by Guite** [comment]
Nice!

**Comment by paustian** [comment]
Done, unless someone wants something else, this works pretty well. If you want comment counts above the actual comments, you need to drop it into the hook first
