### ISSUE TITLE
Different use of the table between <4.0.0 and 4.0.0

### ISSUE THREAD

**Issue by KratorD** [paustian/EZComments#9]
I have noticed differences in the use of the table between the previous versions of <4, and the v4.
"uid" vrs "owneruid". 
In previous version, an user registered was saved in the field "uid". Now the field used is "owneruid".
Edit: Extraction of https://github.com/zikula-modules/EZComments/blob/c230caf3fd25a8861456a10a97df087ab447f310/docs/changelog.txt#L63
`- New database structure. Added field "owneruid". You can
       specify a new parameter "owneruid" whenever you integrate
       EZComments. EZComments will store this value as "content
       owner" and allow this user to moderate all comments for
       his content.`

So that the username appears in the comment it is necessary that the field "anonname" is filled. In previous versions, this field it's not neccesary.

I'm not sure, but i believe that the fields "anonname", "anonmail" and "anonwebsite" was used for user not registered in the site.
Edit: `- Added option to require anonymous commenters to provide a 'name'` `1.2  - Added additional field for anonymous users website` `- Added anonymous users able to define name and email address`

Thanks.

**Comment by paustian** [comment]
I am not really clear on what needs to happen here for backward compatibility. Let me know.

**Comment by KratorD** [comment]
Really, i cant remember it. I think that I wrote this because I transported the old records of ezcomments.
Then, I started using the new version and I checked that the comments were not seen because they were in fields that now seems not to be used in this version.

Example (1):
In old version, you wrote a comment and it was stored in the field "uid", now is stored in "owneruid".
So, the field "uid" is used in this version? is it needed?

On the other hand, the field "anonname" MUST be filled with the username to appear in the template even if you are a registered user and your id is filled in "ownerid". I think that this field (anonname) must to be used ONLY for unregistered user. Is it correct?

A lot of thanks for your job in this module. It is very much appreciated.

**Comment by paustian** [comment]
@KratorD I think I will probably leave this for now. I don't really think there is a huge number of users looking to upgrade. Correct me if I am wrong. I can put the uid in both ownerid and uid. I tried to leave the table structure the same as it was because that leads to upgrade headaches. It's easy to make a change so that the uid is stored in both places, but they are redundant and I use ownerid. I was never able to figure out why both were included in the table. In a future version I can get rid of the uid field.

Yes, anonname is only used for unregistered users. The templates are now smart enough to know who wrote it and fill in the correct data.

**Comment by KratorD** [comment]
Yes, it's correct. Really I wrote this because if "uid" and "ownerid" are the same, you could delete one of them and it use you current field.
About anonname, I tried to tell you that it was being used incorrectly, because when you wrote (as a registered user), a comment, this "anonname" field was informed with your username. But you already have that information in "uid", right? In fact this was the field that was used to put the nickname in the comment.
If this is already corrected, I understand that you can close this issue.
Thanks for all :)

**Comment by paustian** [comment]
One clarification. The user "name" that is entered in anonname is the name that was put in the dialog. While in many cases this will be the username, for EZComments it doesn't have to be. If you are logged in, your uid is going to be recorded, but anonname does not have to be your username. This gives folks the option of being more discreet if they don't want to put their username down.
